import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e8",
        "surface": "#f7f9ff",
        "on-secondary-fixed": "#151c22",
        "primary-fixed-dim": "#a2c9ff",
        "on-surface": "#181c20",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001c38",
        "on-background": "#181c20",
        "surface-container-low": "#f1f4f9",
        "on-tertiary-fixed": "#002115",
        "surface-tint": "#0060a9",
        "tertiary-container": "#00855f",
        "on-secondary-fixed-variant": "#41484e",
        "on-primary-container": "#fdfcff",
        "primary": "#005ea5",
        "outline-variant": "#c0c7d4",
        "tertiary-fixed-dim": "#50dea9",
        "on-secondary-container": "#5e656c",
        "inverse-primary": "#a2c9ff",
        "secondary-fixed": "#dce3ec",
        "primary-fixed": "#d3e4ff",
        "tertiary-fixed": "#70fbc4",
        "surface-container": "#ebeef3",
        "surface-container-high": "#e5e8ee",
        "on-primary": "#ffffff",
        "surface-dim": "#d7dadf",
        "on-tertiary": "#ffffff",
        "background": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404752",
        "tertiary": "#00694b",
        "surface-bright": "#f7f9ff",
        "inverse-surface": "#2d3135",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004881",
        "secondary": "#585f66",
        "inverse-on-surface": "#eef1f6",
        "secondary-container": "#dce3ec",
        "secondary-fixed-dim": "#c0c7cf",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005139",
        "primary-container": "#0677ce",
        "outline": "#717783",
        "surface-variant": "#e0e3e8",
        "error": "#ba1a1a",
        "on-tertiary-container": "#f5fff7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "1.5rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        "space-md": "0.75rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-lg": "1rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["0.8125rem", {"lineHeight": "1.25rem", "fontWeight": "400"}],
        "data-mono": ["0.8125rem", {"lineHeight": "1.25rem", "fontWeight": "400"}],
        "label-sm": ["0.6875rem", {"lineHeight": "0.875rem", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "label-lg": ["0.875rem", {"lineHeight": "1.25rem", "fontWeight": "600"}],
        "headline-sm": ["1.125rem", {"lineHeight": "1.5rem", "letterSpacing": "-0.005em", "fontWeight": "600"}],
        "headline-xl": ["2rem", {"lineHeight": "2.5rem", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["1rem", {"lineHeight": "1.5rem", "fontWeight": "400"}],
        "label-md": ["0.75rem", {"lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-lg": ["1.5rem", {"lineHeight": "2rem", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "body-md": ["0.875rem", {"lineHeight": "1.375rem", "fontWeight": "400"}],
        "headline-md": ["1.25rem", {"lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
export default config;
